<a href="https://colab.research.google.com/github/SAT3A/UC-Numpy/blob/Question/Q20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import numpy as np
 
 
print(np.diag(np.arange(6)))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


## **BEST SOLUTION**

In [52]:
import numpy as np
 
 
print(np.diag(np.arange(6)))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]
