<a href="https://colab.research.google.com/github/SAT3A/UC-Numpy/blob/Question/Q24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import numpy as np
 
 
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


## **BEST SOLUTION**

In [60]:
import numpy as np
 
 
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
