<a href="https://colab.research.google.com/github/SAT3A/UC-Numpy/blob/Question/Q41.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:
import numpy as np
 
 
A = np.array([[4, 2, 1],
              [6, 4, 2]])
 
print(np.expand_dims(A, axis=0))

[[[4 2 1]
  [6 4 2]]]


## **BEST SOLUTION**

In [97]:
import numpy as np
 
 
A = np.array([[4, 2, 1],
              [6, 4, 2]])
 
print(np.expand_dims(A, axis=0))

[[[4 2 1]
  [6 4 2]]]
