<a href="https://colab.research.google.com/github/SAT3A/UC-Numpy/blob/Question/Q48ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [110]:
import numpy as np
 
 
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[::-1, ::-1])

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


## **BEST SOLUTION**

In [111]:
import numpy as np
 
 
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[::-1, ::-1])

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
