<a href="https://colab.research.google.com/github/SAT3A/UC-Numpy/blob/Question/Q61.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [136]:
import numpy as np
 
 
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
 
print((A + B) / 2)

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


## **BEST SOLUTION**

In [139]:
import numpy as np
 
 
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
 
print((A + B) / 2)

## ANOTHER SOLUTION

print("\n")

import numpy as np
 
 
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
 
print(np.divide(np.add(A, B), 2))

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]
