<a href="https://colab.research.google.com/github/SAT3A/UC-Numpy/blob/Question/Q62.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [140]:
import numpy as np
 
 
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
 
print(A * B)


[[12 12 18 10]
 [30  9  2 30]]


## **BEST SOLUTION**

In [141]:
import numpy as np
 
 
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
 
print(A * B)


## ANOTHER SOLUTION

print("\n")

import numpy as np
 
 
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
 
print(np.multiply(A, B))

[[12 12 18 10]
 [30  9  2 30]]


[[12 12 18 10]
 [30  9  2 30]]
