<a href="https://colab.research.google.com/github/SAT3A/UC-Numpy/blob/Question/Q63.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [143]:
import numpy as np
 
 
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
 
print(np.sqrt(A))

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]


## **BEST SOLUTION**

In [142]:
import numpy as np
 
 
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
 
print(np.sqrt(A))

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]
