<a href="https://colab.research.google.com/github/SAT3A/UC-Numpy/blob/Question/Q68.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [152]:
import numpy as np
 
 
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
 
print(np.linalg.inv(A))

[[-0.21393035  0.75621891  0.23880597]
 [ 0.05970149  0.04477612  0.11940299]
 [ 0.09950249 -0.25870647 -0.13432836]]


## **BEST SOLUTION**

In [153]:
import numpy as np
 
 
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
 
print(np.linalg.inv(A))

[[-0.21393035  0.75621891  0.23880597]
 [ 0.05970149  0.04477612  0.11940299]
 [ 0.09950249 -0.25870647 -0.13432836]]
