<a href="https://colab.research.google.com/github/SAT3A/UC-Numpy/blob/Question/Q76.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [168]:
import numpy as np
 
 
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])
 
print(np.polyadd(W, Q))
print(np.polysub(W, Q))
print(np.polymul(W, Q))
print(np.polyadd(W, 2 * Q))

[2 8 0 2]
[-2  0 10  0]
[  8  26   2 -17   0   1]
[ 4 12 -5  3]


## **BEST SOLUTION**

In [169]:
import numpy as np
 
 
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])
 
print(np.polyadd(W, Q))
print(np.polysub(W, Q))
print(np.polymul(W, Q))
print(np.polyadd(W, 2 * Q))

[2 8 0 2]
[-2  0 10  0]
[  8  26   2 -17   0   1]
[ 4 12 -5  3]
