<a href="https://colab.research.google.com/github/SAT3A/UC-Numpy/blob/Question/Q9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
 
 
print(np.zeros(shape=(4, 4), dtype='int'))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## **BEST SOLUTION**

In [26]:
import numpy as np
 
 
print(np.zeros(shape=(4, 4), dtype='int'))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
