<a href="https://colab.research.google.com/github/SAT3A/UC-Numpy/blob/Question/Q99.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [215]:
import numpy as np
 
 
np.set_printoptions(suppress=True)
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])
 
print(playway_values[playway_values[:, 4].argsort()[::-1]][:10])

[[   210.     229.     198.8    211.  100412.      30.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   264.     280.     251.     270.   70136.      29. ]
 [   305.     324.5    283.5    310.   64081.      41. ]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   313.     330.     295.     304.   46724.      35. ]]


## **BEST SOLUTION**

In [216]:
import numpy as np
 
 
np.set_printoptions(suppress=True)
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])
 
print(playway_values[playway_values[:, 4].argsort()[::-1]][:10])

[[   210.     229.     198.8    211.  100412.      30.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   264.     280.     251.     270.   70136.      29. ]
 [   305.     324.5    283.5    310.   64081.      41. ]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   313.     330.     295.     304.   46724.      35. ]]
